# Generated by Django 5.2.6 on 2026-09-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
