# Generated by Django 5.2.6 on 2026-07-18 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id of subcategory', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL friendly unique name', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description about subCategory', null=True)),
                ('status', models.BooleanField(default=True, help_text='True = Active, False = Inactive')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Subcategory creation date.')),
                ('category_name', models.ForeignKey(db_column='categories', help_text='Reference to parent category.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categoryapp.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'db_table': 'subcategory',
            },
        ),
    ]
