# Generated by Django 5.2.6 on 2026-08-12 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='BrandImage/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='productsImage/')),
                ('rating', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(db_column='Brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categoryapp.brand')),
                ('category', models.ForeignKey(db_column='categories_id', help_text='Reference to parent category.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categoryapp.category')),
                ('subcategory', models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categoryapp.subcategory')),
            ],
        ),
    ]
